import "./globals.css";
import VercelToolbarHider from './components/VercelToolbarHider'; // Đường dẫn đúng tới component

export const metadata = {
  title: "Thông tin nhân sự 10 Group",
  description: "Generated by create next app",
  icons: {
    icon: "/mesi.svg",
    apple: "/mesi.svg",
    other: [
      { rel: "icon", type: "image/svg+xml", url: "/mesi.svg" },
      { rel: "manifest", url: "/manifest.json" }
    ]
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        {/* Dòng code dưới đây được thêm vào để ẩn Vercel Toolbar */}
        <VercelToolbarHider />
      </body>
    </html>
  );
}